#include "core/cuda/kernels/open_cuda_vb_kernels.h"

#include <cstdint>
#include <limits>
#include <mutex>

namespace studiocast::cuda::kernels {
namespace {

// Embedded PTX for kernels in open_cuda_vb_kernels.cu.
// Generated with:
//   nvcc -ptx -O3 --use_fast_math -arch=compute_52 open_cuda_vb_kernels.cu
static constexpr const char *kOpenCudaVbPtx = R"ptx(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-30672275
// Cuda compilation tools, release 11.5, V11.5.119
// Based on NVVM 7.0.1
//

.version 7.5
.target sm_52
.address_size 64

	// .globl	resize_bilinear_f32_1

.visible .entry resize_bilinear_f32_1(
	.param .u64 resize_bilinear_f32_1_param_0,
	.param .u32 resize_bilinear_f32_1_param_1,
	.param .u32 resize_bilinear_f32_1_param_2,
	.param .u32 resize_bilinear_f32_1_param_3,
	.param .u64 resize_bilinear_f32_1_param_4,
	.param .u32 resize_bilinear_f32_1_param_5,
	.param .u32 resize_bilinear_f32_1_param_6,
	.param .u32 resize_bilinear_f32_1_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<29>;
	.reg .b32 	%r<29>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd1, [resize_bilinear_f32_1_param_0];
	ld.param.u32 	%r3, [resize_bilinear_f32_1_param_1];
	ld.param.u32 	%r4, [resize_bilinear_f32_1_param_2];
	ld.param.u32 	%r5, [resize_bilinear_f32_1_param_3];
	ld.param.u64 	%rd2, [resize_bilinear_f32_1_param_4];
	ld.param.u32 	%r6, [resize_bilinear_f32_1_param_5];
	ld.param.u32 	%r7, [resize_bilinear_f32_1_param_6];
	ld.param.u32 	%r8, [resize_bilinear_f32_1_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	setp.ge.s32 	%p1, %r1, %r7;
	setp.ge.s32 	%p2, %r2, %r8;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd1;
	cvta.to.global.u64 	%rd4, %rd2;
	cvt.rn.f32.u32 	%f1, %r7;
	cvt.rn.f32.u32 	%f2, %r4;
	div.approx.ftz.f32 	%f3, %f2, %f1;
	cvt.rn.f32.u32 	%f4, %r8;
	cvt.rn.f32.u32 	%f5, %r5;
	div.approx.ftz.f32 	%f6, %f5, %f4;
	cvt.rn.f32.s32 	%f7, %r1;
	add.ftz.f32 	%f8, %f7, 0f3F000000;
	fma.rn.ftz.f32 	%f9, %f8, %f3, 0fBF000000;
	cvt.rn.f32.s32 	%f10, %r2;
	add.ftz.f32 	%f11, %f10, 0f3F000000;
	fma.rn.ftz.f32 	%f12, %f11, %f6, 0fBF000000;
	cvt.rmi.ftz.f32.f32 	%f13, %f9;
	cvt.rzi.ftz.s32.f32 	%r15, %f13;
	cvt.rmi.ftz.f32.f32 	%f14, %f12;
	cvt.rzi.ftz.s32.f32 	%r16, %f14;
	cvt.rn.f32.s32 	%f15, %r15;
	sub.ftz.f32 	%f16, %f9, %f15;
	cvt.rn.f32.s32 	%f17, %r16;
	sub.ftz.f32 	%f18, %f12, %f17;
	setp.lt.s32 	%p4, %r15, 0;
	add.s32 	%r17, %r4, -1;
	min.s32 	%r18, %r15, %r17;
	selp.b32 	%r19, 0, %r18, %p4;
	setp.lt.s32 	%p5, %r16, 0;
	add.s32 	%r20, %r5, -1;
	min.s32 	%r21, %r16, %r20;
	selp.b32 	%r22, 0, %r21, %p5;
	add.s32 	%r23, %r19, 1;
	setp.lt.s32 	%p6, %r19, -1;
	min.s32 	%r24, %r23, %r17;
	selp.b32 	%r25, 0, %r24, %p6;
	add.s32 	%r26, %r22, 1;
	setp.lt.s32 	%p7, %r22, -1;
	min.s32 	%r27, %r26, %r20;
	selp.b32 	%r28, 0, %r27, %p7;
	cvt.s64.s32 	%rd5, %r22;
	cvt.u64.u32 	%rd6, %r3;
	mul.lo.s64 	%rd7, %rd5, %rd6;
	add.s64 	%rd8, %rd3, %rd7;
	cvt.s64.s32 	%rd9, %r28;
	mul.lo.s64 	%rd10, %rd9, %rd6;
	add.s64 	%rd11, %rd3, %rd10;
	mul.wide.s32 	%rd12, %r19, 4;
	add.s64 	%rd13, %rd8, %rd12;
	mul.wide.s32 	%rd14, %r25, 4;
	add.s64 	%rd15, %rd8, %rd14;
	add.s64 	%rd16, %rd11, %rd12;
	add.s64 	%rd17, %rd11, %rd14;
	ld.global.f32 	%f19, [%rd15];
	ld.global.f32 	%f20, [%rd13];
	sub.ftz.f32 	%f21, %f19, %f20;
	fma.rn.ftz.f32 	%f22, %f16, %f21, %f20;
	ld.global.f32 	%f23, [%rd17];
	ld.global.f32 	%f24, [%rd16];
	sub.ftz.f32 	%f25, %f23, %f24;
	fma.rn.ftz.f32 	%f26, %f16, %f25, %f24;
	sub.ftz.f32 	%f27, %f26, %f22;
	fma.rn.ftz.f32 	%f28, %f18, %f27, %f22;
	cvt.u64.u32 	%rd18, %r6;
	cvt.s64.s32 	%rd19, %r2;
	mul.lo.s64 	%rd20, %rd18, %rd19;
	add.s64 	%rd21, %rd4, %rd20;
	mul.wide.s32 	%rd22, %r1, 4;
	add.s64 	%rd23, %rd21, %rd22;
	st.global.f32 	[%rd23], %f28;

$L__BB0_2:
	ret;

}
	// .globl	box_blur_h_u8x3
.visible .entry box_blur_h_u8x3(
	.param .u64 box_blur_h_u8x3_param_0,
	.param .u32 box_blur_h_u8x3_param_1,
	.param .u32 box_blur_h_u8x3_param_2,
	.param .u32 box_blur_h_u8x3_param_3,
	.param .u64 box_blur_h_u8x3_param_4,
	.param .u32 box_blur_h_u8x3_param_5,
	.param .u32 box_blur_h_u8x3_param_6
)
{
	.reg .pred 	%p<13>;
	.reg .b32 	%r<135>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd5, [box_blur_h_u8x3_param_0];
	ld.param.u32 	%r43, [box_blur_h_u8x3_param_1];
	ld.param.u32 	%r44, [box_blur_h_u8x3_param_2];
	ld.param.u32 	%r47, [box_blur_h_u8x3_param_3];
	ld.param.u64 	%rd4, [box_blur_h_u8x3_param_4];
	ld.param.u32 	%r45, [box_blur_h_u8x3_param_5];
	ld.param.u32 	%r46, [box_blur_h_u8x3_param_6];
	cvta.to.global.u64 	%rd1, %rd5;
	mov.u32 	%r48, %ntid.x;
	mov.u32 	%r49, %ctaid.x;
	mul.lo.s32 	%r1, %r49, %r48;
	mov.u32 	%r50, %tid.x;
	add.s32 	%r2, %r1, %r50;
	mov.u32 	%r51, %ntid.y;
	mov.u32 	%r52, %ctaid.y;
	mov.u32 	%r53, %tid.y;
	mad.lo.s32 	%r3, %r52, %r51, %r53;
	setp.ge.s32 	%p1, %r2, %r44;
	setp.ge.s32 	%p2, %r3, %r47;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB1_8;

	mov.u32 	%r132, 0;
	max.s32 	%r4, %r46, 0;
	shl.b32 	%r5, %r4, 1;
	or.b32  	%r6, %r5, 1;
	cvt.u64.u32 	%rd6, %r43;
	cvt.s64.s32 	%rd2, %r3;
	mul.lo.s64 	%rd3, %rd6, %rd2;
	neg.s32 	%r123, %r4;
	setp.lt.s32 	%p4, %r4, %r123;
	mov.u32 	%r133, %r132;
	mov.u32 	%r134, %r132;
	@%p4 bra 	$L__BB1_7;

	add.s32 	%r8, %r44, -1;
	and.b32  	%r9, %r6, 3;
	setp.lt.u32 	%p5, %r4, 2;
	mov.u32 	%r134, 0;
	mov.u32 	%r133, %r134;
	mov.u32 	%r132, %r134;
	@%p5 bra 	$L__BB1_5;

	add.s32 	%r63, %r2, 3;
	sub.s32 	%r118, %r63, %r4;
	add.s32 	%r64, %r9, -1;
	sub.s32 	%r117, %r64, %r5;

$L__BB1_4:
	add.s32 	%r65, %r2, %r123;
	setp.lt.s32 	%p6, %r65, 0;
	min.s32 	%r66, %r65, %r8;
	mul.lo.s32 	%r67, %r66, 3;
	selp.b32 	%r68, 0, %r67, %p6;
	cvt.s64.s32 	%rd7, %r68;
	add.s64 	%rd8, %rd3, %rd7;
	add.s64 	%rd9, %rd1, %rd8;
	ld.global.u8 	%r69, [%rd9];
	add.s32 	%r70, %r132, %r69;
	ld.global.u8 	%r71, [%rd9+1];
	add.s32 	%r72, %r133, %r71;
	ld.global.u8 	%r73, [%rd9+2];
	add.s32 	%r74, %r134, %r73;
	add.s32 	%r75, %r118, -2;
	setp.lt.s32 	%p7, %r75, 0;
	min.s32 	%r76, %r75, %r8;
	mul.lo.s32 	%r77, %r76, 3;
	selp.b32 	%r78, 0, %r77, %p7;
	cvt.s64.s32 	%rd10, %r78;
	add.s64 	%rd11, %rd3, %rd10;
	add.s64 	%rd12, %rd1, %rd11;
	ld.global.u8 	%r79, [%rd12];
	add.s32 	%r80, %r70, %r79;
	ld.global.u8 	%r81, [%rd12+1];
	add.s32 	%r82, %r72, %r81;
	ld.global.u8 	%r83, [%rd12+2];
	add.s32 	%r84, %r74, %r83;
	add.s32 	%r85, %r118, -1;
	setp.lt.s32 	%p8, %r85, 0;
	min.s32 	%r86, %r85, %r8;
	mul.lo.s32 	%r87, %r86, 3;
	selp.b32 	%r88, 0, %r87, %p8;
	cvt.s64.s32 	%rd13, %r88;
	add.s64 	%rd14, %rd3, %rd13;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.u8 	%r89, [%rd15];
	add.s32 	%r90, %r80, %r89;
	ld.global.u8 	%r91, [%rd15+1];
	add.s32 	%r92, %r82, %r91;
	ld.global.u8 	%r93, [%rd15+2];
	add.s32 	%r94, %r84, %r93;
	min.s32 	%r95, %r118, %r8;
	mul.lo.s32 	%r96, %r95, 3;
	setp.lt.s32 	%p9, %r118, 0;
	selp.b32 	%r97, 0, %r96, %p9;
	cvt.s64.s32 	%rd16, %r97;
	add.s64 	%rd17, %rd3, %rd16;
	add.s64 	%rd18, %rd1, %rd17;
	ld.global.u8 	%r98, [%rd18];
	add.s32 	%r132, %r90, %r98;
	ld.global.u8 	%r99, [%rd18+1];
	add.s32 	%r133, %r92, %r99;
	ld.global.u8 	%r100, [%rd18+2];
	add.s32 	%r134, %r94, %r100;
	add.s32 	%r123, %r123, 4;
	add.s32 	%r118, %r118, 4;
	add.s32 	%r117, %r117, 4;
	setp.ne.s32 	%p10, %r117, 0;
	@%p10 bra 	$L__BB1_4;

$L__BB1_5:
	add.s32 	%r127, %r9, -1;
	add.s32 	%r102, %r50, %r123;
	add.s32 	%r128, %r102, %r1;

$L__BB1_6:
	.pragma "nounroll";
	min.s32 	%r103, %r128, %r8;
	mul.lo.s32 	%r104, %r103, 3;
	setp.lt.s32 	%p11, %r128, 0;
	selp.b32 	%r105, 0, %r104, %p11;
	cvt.s64.s32 	%rd19, %r105;
	add.s64 	%rd20, %rd3, %rd19;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.u8 	%r106, [%rd21];
	add.s32 	%r132, %r132, %r106;
	ld.global.u8 	%r107, [%rd21+1];
	add.s32 	%r133, %r133, %r107;
	ld.global.u8 	%r108, [%rd21+2];
	add.s32 	%r134, %r134, %r108;
	add.s32 	%r128, %r128, 1;
	add.s32 	%r127, %r127, -1;
	setp.ne.s32 	%p12, %r127, -1;
	@%p12 bra 	$L__BB1_6;

$L__BB1_7:
	cvt.u64.u32 	%rd22, %r45;
	mul.lo.s64 	%rd23, %rd22, %rd2;
	shr.u32 	%r109, %r6, 1;
	add.s32 	%r110, %r132, %r109;
	div.u32 	%r111, %r110, %r6;
	mul.lo.s32 	%r112, %r2, 3;
	cvt.s64.s32 	%rd24, %r112;
	add.s64 	%rd25, %rd23, %rd24;
	cvta.to.global.u64 	%rd26, %rd4;
	add.s64 	%rd27, %rd26, %rd25;
	st.global.u8 	[%rd27], %r111;
	add.s32 	%r113, %r133, %r109;
	div.u32 	%r114, %r113, %r6;
	st.global.u8 	[%rd27+1], %r114;
	add.s32 	%r115, %r134, %r109;
	div.u32 	%r116, %r115, %r6;
	st.global.u8 	[%rd27+2], %r116;

$L__BB1_8:
	ret;

}
	// .globl	box_blur_v_u8x3
.visible .entry box_blur_v_u8x3(
	.param .u64 box_blur_v_u8x3_param_0,
	.param .u32 box_blur_v_u8x3_param_1,
	.param .u32 box_blur_v_u8x3_param_2,
	.param .u32 box_blur_v_u8x3_param_3,
	.param .u64 box_blur_v_u8x3_param_4,
	.param .u32 box_blur_v_u8x3_param_5,
	.param .u32 box_blur_v_u8x3_param_6
)
{
	.reg .pred 	%p<13>;
	.reg .b32 	%r<130>;
	.reg .b64 	%rd<46>;


	ld.param.u64 	%rd6, [box_blur_v_u8x3_param_0];
	ld.param.u32 	%r45, [box_blur_v_u8x3_param_1];
	ld.param.u32 	%r49, [box_blur_v_u8x3_param_2];
	ld.param.u32 	%r46, [box_blur_v_u8x3_param_3];
	ld.param.u64 	%rd5, [box_blur_v_u8x3_param_4];
	ld.param.u32 	%r47, [box_blur_v_u8x3_param_5];
	ld.param.u32 	%r48, [box_blur_v_u8x3_param_6];
	cvta.to.global.u64 	%rd1, %rd6;
	mov.u32 	%r50, %ntid.x;
	mov.u32 	%r51, %ctaid.x;
	mov.u32 	%r52, %tid.x;
	mad.lo.s32 	%r1, %r51, %r50, %r52;
	mov.u32 	%r53, %ntid.y;
	mov.u32 	%r54, %ctaid.y;
	mul.lo.s32 	%r2, %r54, %r53;
	mov.u32 	%r3, %tid.y;
	add.s32 	%r4, %r2, %r3;
	setp.ge.s32 	%p1, %r1, %r49;
	setp.ge.s32 	%p2, %r4, %r46;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB2_8;

	mov.u32 	%r127, 0;
	max.s32 	%r5, %r48, 0;
	shl.b32 	%r6, %r5, 1;
	or.b32  	%r7, %r6, 1;
	neg.s32 	%r118, %r5;
	setp.lt.s32 	%p4, %r5, %r118;
	mul.lo.s32 	%r9, %r1, 3;
	cvt.s64.s32 	%rd2, %r9;
	add.s32 	%r58, %r9, 1;
	cvt.s64.s32 	%rd3, %r58;
	mov.u32 	%r128, %r127;
	mov.u32 	%r129, %r127;
	@%p4 bra 	$L__BB2_7;

	add.s32 	%r10, %r46, -1;
	cvt.u64.u32 	%rd4, %r45;
	and.b32  	%r11, %r7, 3;
	setp.lt.u32 	%p5, %r5, 2;
	mov.u32 	%r129, 0;
	mov.u32 	%r128, %r129;
	mov.u32 	%r127, %r129;
	@%p5 bra 	$L__BB2_5;

	add.s32 	%r65, %r4, 3;
	sub.s32 	%r113, %r65, %r5;
	add.s32 	%r66, %r11, -1;
	sub.s32 	%r112, %r66, %r6;

$L__BB2_4:
	add.s32 	%r67, %r4, %r118;
	setp.lt.s32 	%p6, %r67, 0;
	min.s32 	%r68, %r67, %r10;
	selp.b32 	%r69, 0, %r68, %p6;
	cvt.s64.s32 	%rd7, %r69;
	mul.lo.s64 	%rd8, %rd7, %rd4;
	add.s64 	%rd9, %rd8, %rd2;
	add.s64 	%rd10, %rd1, %rd9;
	ld.global.u8 	%r70, [%rd10];
	add.s32 	%r71, %r127, %r70;
	add.s64 	%rd11, %rd8, %rd3;
	add.s64 	%rd12, %rd1, %rd11;
	ld.global.u8 	%r72, [%rd12];
	add.s32 	%r73, %r128, %r72;
	ld.global.u8 	%r74, [%rd12+1];
	add.s32 	%r75, %r129, %r74;
	add.s32 	%r76, %r113, -2;
	setp.lt.s32 	%p7, %r76, 0;
	min.s32 	%r77, %r76, %r10;
	selp.b32 	%r78, 0, %r77, %p7;
	cvt.s64.s32 	%rd13, %r78;
	mul.lo.s64 	%rd14, %rd13, %rd4;
	add.s64 	%rd15, %rd14, %rd2;
	add.s64 	%rd16, %rd1, %rd15;
	ld.global.u8 	%r79, [%rd16];
	add.s32 	%r80, %r71, %r79;
	add.s64 	%rd17, %rd14, %rd3;
	add.s64 	%rd18, %rd1, %rd17;
	ld.global.u8 	%r81, [%rd18];
	add.s32 	%r82, %r73, %r81;
	ld.global.u8 	%r83, [%rd18+1];
	add.s32 	%r84, %r75, %r83;
	add.s32 	%r85, %r113, -1;
	setp.lt.s32 	%p8, %r85, 0;
	min.s32 	%r86, %r85, %r10;
	selp.b32 	%r87, 0, %r86, %p8;
	cvt.s64.s32 	%rd19, %r87;
	mul.lo.s64 	%rd20, %rd19, %rd4;
	add.s64 	%rd21, %rd20, %rd2;
	add.s64 	%rd22, %rd1, %rd21;
	ld.global.u8 	%r88, [%rd22];
	add.s32 	%r89, %r80, %r88;
	add.s64 	%rd23, %rd20, %rd3;
	add.s64 	%rd24, %rd1, %rd23;
	ld.global.u8 	%r90, [%rd24];
	add.s32 	%r91, %r82, %r90;
	ld.global.u8 	%r92, [%rd24+1];
	add.s32 	%r93, %r84, %r92;
	min.s32 	%r94, %r113, %r10;
	setp.lt.s32 	%p9, %r113, 0;
	selp.b32 	%r95, 0, %r94, %p9;
	cvt.s64.s32 	%rd25, %r95;
	mul.lo.s64 	%rd26, %rd25, %rd4;
	add.s64 	%rd27, %rd26, %rd2;
	add.s64 	%rd28, %rd1, %rd27;
	ld.global.u8 	%r96, [%rd28];
	add.s32 	%r127, %r89, %r96;
	add.s64 	%rd29, %rd26, %rd3;
	add.s64 	%rd30, %rd1, %rd29;
	ld.global.u8 	%r97, [%rd30];
	add.s32 	%r128, %r91, %r97;
	ld.global.u8 	%r98, [%rd30+1];
	add.s32 	%r129, %r93, %r98;
	add.s32 	%r118, %r118, 4;
	add.s32 	%r113, %r113, 4;
	add.s32 	%r112, %r112, 4;
	setp.ne.s32 	%p10, %r112, 0;
	@%p10 bra 	$L__BB2_4;

$L__BB2_5:
	add.s32 	%r122, %r11, -1;
	add.s32 	%r99, %r3, %r118;
	add.s32 	%r123, %r99, %r2;

$L__BB2_6:
	.pragma "nounroll";
	min.s32 	%r100, %r123, %r10;
	setp.lt.s32 	%p11, %r123, 0;
	selp.b32 	%r101, 0, %r100, %p11;
	cvt.s64.s32 	%rd31, %r101;
	mul.lo.s64 	%rd32, %rd31, %rd4;
	add.s64 	%rd33, %rd32, %rd2;
	add.s64 	%rd34, %rd1, %rd33;
	ld.global.u8 	%r102, [%rd34];
	add.s32 	%r127, %r127, %r102;
	add.s64 	%rd35, %rd32, %rd3;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.u8 	%r103, [%rd36];
	add.s32 	%r128, %r128, %r103;
	ld.global.u8 	%r104, [%rd36+1];
	add.s32 	%r129, %r129, %r104;
	add.s32 	%r123, %r123, 1;
	add.s32 	%r122, %r122, -1;
	setp.ne.s32 	%p12, %r122, -1;
	@%p12 bra 	$L__BB2_6;

$L__BB2_7:
	cvta.to.global.u64 	%rd37, %rd5;
	cvt.u64.u32 	%rd38, %r47;
	cvt.s64.s32 	%rd39, %r4;
	mul.lo.s64 	%rd40, %rd38, %rd39;
	shr.u32 	%r105, %r7, 1;
	add.s32 	%r106, %r127, %r105;
	div.u32 	%r107, %r106, %r7;
	add.s64 	%rd41, %rd40, %rd2;
	add.s64 	%rd42, %rd37, %rd41;
	st.global.u8 	[%rd42], %r107;
	add.s32 	%r108, %r128, %r105;
	div.u32 	%r109, %r108, %r7;
	st.global.u8 	[%rd42+1], %r109;
	add.s32 	%r110, %r129, %r105;
	div.u32 	%r111, %r110, %r7;
	st.global.u8 	[%rd42+2], %r111;

$L__BB2_8:
	ret;

}
	// .globl	box_blur_h_f32_1
.visible .entry box_blur_h_f32_1(
	.param .u64 box_blur_h_f32_1_param_0,
	.param .u32 box_blur_h_f32_1_param_1,
	.param .u32 box_blur_h_f32_1_param_2,
	.param .u32 box_blur_h_f32_1_param_3,
	.param .u64 box_blur_h_f32_1_param_4,
	.param .u32 box_blur_h_f32_1_param_5,
	.param .u32 box_blur_h_f32_1_param_6
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<22>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd3, [box_blur_h_f32_1_param_0];
	ld.param.u32 	%r22, [box_blur_h_f32_1_param_1];
	ld.param.u32 	%r23, [box_blur_h_f32_1_param_2];
	ld.param.u32 	%r26, [box_blur_h_f32_1_param_3];
	ld.param.u64 	%rd4, [box_blur_h_f32_1_param_4];
	ld.param.u32 	%r24, [box_blur_h_f32_1_param_5];
	ld.param.u32 	%r25, [box_blur_h_f32_1_param_6];
	mov.u32 	%r27, %ntid.x;
	mov.u32 	%r28, %ctaid.x;
	mov.u32 	%r29, %tid.x;
	mad.lo.s32 	%r1, %r28, %r27, %r29;
	mov.u32 	%r30, %ntid.y;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %tid.y;
	mad.lo.s32 	%r2, %r31, %r30, %r32;
	setp.ge.s32 	%p1, %r1, %r23;
	setp.ge.s32 	%p2, %r2, %r26;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB3_8;

	max.s32 	%r3, %r25, 0;
	shl.b32 	%r33, %r3, 1;
	or.b32  	%r4, %r33, 1;
	cvt.s64.s32 	%rd1, %r2;
	neg.s32 	%r34, %r3;
	setp.lt.s32 	%p4, %r3, %r34;
	mov.f32 	%f21, 0f00000000;
	@%p4 bra 	$L__BB3_7;

	cvt.u64.u32 	%rd5, %r22;
	mul.lo.s64 	%rd6, %rd5, %rd1;
	cvta.to.global.u64 	%rd7, %rd3;
	add.s64 	%rd2, %rd7, %rd6;
	add.s32 	%r5, %r23, -1;
	sub.s32 	%r51, %r1, %r3;
	not.b32 	%r53, %r3;
	and.b32  	%r35, %r4, 3;
	add.s32 	%r48, %r35, -1;

$L__BB3_3:
	.pragma "nounroll";
	min.s32 	%r36, %r51, %r5;
	setp.lt.s32 	%p5, %r51, 0;
	selp.b32 	%r37, 0, %r36, %p5;
	mul.wide.s32 	%rd8, %r37, 4;
	add.s64 	%rd9, %rd2, %rd8;
	ld.global.f32 	%f8, [%rd9];
	add.ftz.f32 	%f21, %f21, %f8;
	add.s32 	%r51, %r51, 1;
	add.s32 	%r53, %r53, 1;
	add.s32 	%r48, %r48, -1;
	setp.ne.s32 	%p6, %r48, -1;
	@%p6 bra 	$L__BB3_3;

	setp.lt.u32 	%p7, %r3, 2;
	@%p7 bra 	$L__BB3_7;

	add.s32 	%r52, %r51, 3;

$L__BB3_6:
	min.s32 	%r38, %r51, %r5;
	setp.lt.s32 	%p8, %r51, 0;
	selp.b32 	%r39, 0, %r38, %p8;
	mul.wide.s32 	%rd10, %r39, 4;
	add.s64 	%rd11, %rd2, %rd10;
	ld.global.f32 	%f9, [%rd11];
	add.ftz.f32 	%f10, %f21, %f9;
	add.s32 	%r40, %r52, -2;
	setp.lt.s32 	%p9, %r40, 0;
	min.s32 	%r41, %r40, %r5;
	selp.b32 	%r42, 0, %r41, %p9;
	mul.wide.s32 	%rd12, %r42, 4;
	add.s64 	%rd13, %rd2, %rd12;
	ld.global.f32 	%f11, [%rd13];
	add.ftz.f32 	%f12, %f10, %f11;
	add.s32 	%r43, %r52, -1;
	setp.lt.s32 	%p10, %r43, 0;
	min.s32 	%r44, %r43, %r5;
	selp.b32 	%r45, 0, %r44, %p10;
	mul.wide.s32 	%rd14, %r45, 4;
	add.s64 	%rd15, %rd2, %rd14;
	ld.global.f32 	%f13, [%rd15];
	add.ftz.f32 	%f14, %f12, %f13;
	min.s32 	%r46, %r52, %r5;
	setp.lt.s32 	%p11, %r52, 0;
	selp.b32 	%r47, 0, %r46, %p11;
	mul.wide.s32 	%rd16, %r47, 4;
	add.s64 	%rd17, %rd2, %rd16;
	ld.global.f32 	%f15, [%rd17];
	add.ftz.f32 	%f21, %f14, %f15;
	add.s32 	%r52, %r52, 4;
	add.s32 	%r51, %r51, 4;
	add.s32 	%r53, %r53, 4;
	setp.lt.s32 	%p12, %r53, %r3;
	@%p12 bra 	$L__BB3_6;

$L__BB3_7:
	cvt.u64.u32 	%rd18, %r24;
	mul.lo.s64 	%rd19, %rd18, %rd1;
	cvta.to.global.u64 	%rd20, %rd4;
	add.s64 	%rd21, %rd20, %rd19;
	mul.wide.s32 	%rd22, %r1, 4;
	add.s64 	%rd23, %rd21, %rd22;
	cvt.rn.f32.s32 	%f16, %r4;
	rcp.approx.ftz.f32 	%f17, %f16;
	mul.ftz.f32 	%f18, %f17, %f21;
	st.global.f32 	[%rd23], %f18;

$L__BB3_8:
	ret;

}
	// .globl	box_blur_v_f32_1
.visible .entry box_blur_v_f32_1(
	.param .u64 box_blur_v_f32_1_param_0,
	.param .u32 box_blur_v_f32_1_param_1,
	.param .u32 box_blur_v_f32_1_param_2,
	.param .u32 box_blur_v_f32_1_param_3,
	.param .u64 box_blur_v_f32_1_param_4,
	.param .u32 box_blur_v_f32_1_param_5,
	.param .u32 box_blur_v_f32_1_param_6
)
{
	.reg .pred 	%p<13>;
	.reg .f32 	%f<22>;
	.reg .b32 	%r<54>;
	.reg .b64 	%rd<35>;


	ld.param.u64 	%rd5, [box_blur_v_f32_1_param_0];
	ld.param.u32 	%r22, [box_blur_v_f32_1_param_1];
	ld.param.u32 	%r26, [box_blur_v_f32_1_param_2];
	ld.param.u32 	%r23, [box_blur_v_f32_1_param_3];
	ld.param.u64 	%rd4, [box_blur_v_f32_1_param_4];
	ld.param.u32 	%r24, [box_blur_v_f32_1_param_5];
	ld.param.u32 	%r25, [box_blur_v_f32_1_param_6];
	cvta.to.global.u64 	%rd1, %rd5;
	mov.u32 	%r27, %ntid.x;
	mov.u32 	%r28, %ctaid.x;
	mov.u32 	%r29, %tid.x;
	mad.lo.s32 	%r1, %r28, %r27, %r29;
	mov.u32 	%r30, %ntid.y;
	mov.u32 	%r31, %ctaid.y;
	mov.u32 	%r32, %tid.y;
	mad.lo.s32 	%r2, %r31, %r30, %r32;
	setp.ge.s32 	%p1, %r1, %r26;
	setp.ge.s32 	%p2, %r2, %r23;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB4_8;

	max.s32 	%r3, %r25, 0;
	shl.b32 	%r33, %r3, 1;
	or.b32  	%r4, %r33, 1;
	neg.s32 	%r34, %r3;
	setp.lt.s32 	%p4, %r3, %r34;
	cvt.s64.s32 	%rd2, %r1;
	mov.f32 	%f21, 0f00000000;
	@%p4 bra 	$L__BB4_7;

	add.s32 	%r5, %r23, -1;
	cvt.u64.u32 	%rd3, %r22;
	sub.s32 	%r51, %r2, %r3;
	not.b32 	%r53, %r3;
	and.b32  	%r35, %r4, 3;
	add.s32 	%r48, %r35, -1;
	shl.b64 	%rd9, %rd2, 2;

$L__BB4_3:
	.pragma "nounroll";
	min.s32 	%r36, %r51, %r5;
	setp.lt.s32 	%p5, %r51, 0;
	selp.b32 	%r37, 0, %r36, %p5;
	cvt.s64.s32 	%rd6, %r37;
	mul.lo.s64 	%rd7, %rd6, %rd3;
	add.s64 	%rd8, %rd1, %rd7;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.f32 	%f8, [%rd10];
	add.ftz.f32 	%f21, %f21, %f8;
	add.s32 	%r51, %r51, 1;
	add.s32 	%r53, %r53, 1;
	add.s32 	%r48, %r48, -1;
	setp.ne.s32 	%p6, %r48, -1;
	@%p6 bra 	$L__BB4_3;

	setp.lt.u32 	%p7, %r3, 2;
	@%p7 bra 	$L__BB4_7;

	add.s32 	%r52, %r51, 3;

$L__BB4_6:
	min.s32 	%r38, %r51, %r5;
	setp.lt.s32 	%p8, %r51, 0;
	selp.b32 	%r39, 0, %r38, %p8;
	cvt.s64.s32 	%rd11, %r39;
	mul.lo.s64 	%rd12, %rd11, %rd3;
	add.s64 	%rd13, %rd1, %rd12;
	add.s64 	%rd15, %rd13, %rd9;
	ld.global.f32 	%f9, [%rd15];
	add.ftz.f32 	%f10, %f21, %f9;
	add.s32 	%r40, %r52, -2;
	setp.lt.s32 	%p9, %r40, 0;
	min.s32 	%r41, %r40, %r5;
	selp.b32 	%r42, 0, %r41, %p9;
	cvt.s64.s32 	%rd16, %r42;
	mul.lo.s64 	%rd17, %rd16, %rd3;
	add.s64 	%rd18, %rd1, %rd17;
	add.s64 	%rd19, %rd18, %rd9;
	ld.global.f32 	%f11, [%rd19];
	add.ftz.f32 	%f12, %f10, %f11;
	add.s32 	%r43, %r52, -1;
	setp.lt.s32 	%p10, %r43, 0;
	min.s32 	%r44, %r43, %r5;
	selp.b32 	%r45, 0, %r44, %p10;
	cvt.s64.s32 	%rd20, %r45;
	mul.lo.s64 	%rd21, %rd20, %rd3;
	add.s64 	%rd22, %rd1, %rd21;
	add.s64 	%rd23, %rd22, %rd9;
	ld.global.f32 	%f13, [%rd23];
	add.ftz.f32 	%f14, %f12, %f13;
	min.s32 	%r46, %r52, %r5;
	setp.lt.s32 	%p11, %r52, 0;
	selp.b32 	%r47, 0, %r46, %p11;
	cvt.s64.s32 	%rd24, %r47;
	mul.lo.s64 	%rd25, %rd24, %rd3;
	add.s64 	%rd26, %rd1, %rd25;
	add.s64 	%rd27, %rd26, %rd9;
	ld.global.f32 	%f15, [%rd27];
	add.ftz.f32 	%f21, %f14, %f15;
	add.s32 	%r52, %r52, 4;
	add.s32 	%r51, %r51, 4;
	add.s32 	%r53, %r53, 4;
	setp.lt.s32 	%p12, %r53, %r3;
	@%p12 bra 	$L__BB4_6;

$L__BB4_7:
	cvt.u64.u32 	%rd28, %r24;
	cvt.s64.s32 	%rd29, %r2;
	mul.lo.s64 	%rd30, %rd28, %rd29;
	cvta.to.global.u64 	%rd31, %rd4;
	add.s64 	%rd32, %rd31, %rd30;
	shl.b64 	%rd33, %rd2, 2;
	add.s64 	%rd34, %rd32, %rd33;
	cvt.rn.f32.s32 	%f16, %r4;
	rcp.approx.ftz.f32 	%f17, %f16;
	mul.ftz.f32 	%f18, %f17, %f21;
	st.global.f32 	[%rd34], %f18;

$L__BB4_8:
	ret;

}
	// .globl	composite_alpha_u8x3_bg
.visible .entry composite_alpha_u8x3_bg(
	.param .u64 composite_alpha_u8x3_bg_param_0,
	.param .u32 composite_alpha_u8x3_bg_param_1,
	.param .u64 composite_alpha_u8x3_bg_param_2,
	.param .u32 composite_alpha_u8x3_bg_param_3,
	.param .u64 composite_alpha_u8x3_bg_param_4,
	.param .u32 composite_alpha_u8x3_bg_param_5,
	.param .u32 composite_alpha_u8x3_bg_param_6,
	.param .u32 composite_alpha_u8x3_bg_param_7,
	.param .u64 composite_alpha_u8x3_bg_param_8,
	.param .u32 composite_alpha_u8x3_bg_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<7>;
	.reg .f32 	%f<27>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<28>;


	ld.param.u64 	%rd1, [composite_alpha_u8x3_bg_param_0];
	ld.param.u32 	%r3, [composite_alpha_u8x3_bg_param_1];
	ld.param.u64 	%rd2, [composite_alpha_u8x3_bg_param_2];
	ld.param.u32 	%r4, [composite_alpha_u8x3_bg_param_3];
	ld.param.u64 	%rd3, [composite_alpha_u8x3_bg_param_4];
	ld.param.u32 	%r5, [composite_alpha_u8x3_bg_param_5];
	ld.param.u32 	%r7, [composite_alpha_u8x3_bg_param_6];
	ld.param.u32 	%r8, [composite_alpha_u8x3_bg_param_7];
	ld.param.u64 	%rd4, [composite_alpha_u8x3_bg_param_8];
	ld.param.u32 	%r6, [composite_alpha_u8x3_bg_param_9];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	setp.ge.s32 	%p1, %r1, %r7;
	setp.ge.s32 	%p2, %r2, %r8;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB5_2;

	cvta.to.global.u64 	%rd5, %rd4;
	cvta.to.global.u64 	%rd6, %rd2;
	cvta.to.global.u64 	%rd7, %rd1;
	cvta.to.global.u64 	%rd8, %rd3;
	cvt.u64.u32 	%rd9, %r3;
	cvt.s64.s32 	%rd10, %r2;
	mul.lo.s64 	%rd11, %rd9, %rd10;
	cvt.u64.u32 	%rd12, %r4;
	mul.lo.s64 	%rd13, %rd12, %rd10;
	cvt.u64.u32 	%rd14, %r5;
	mul.lo.s64 	%rd15, %rd14, %rd10;
	add.s64 	%rd16, %rd8, %rd15;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.f32 	%f1, [%rd18];
	setp.lt.ftz.f32 	%p4, %f1, 0f00000000;
	setp.gt.ftz.f32 	%p5, %f1, 0f3F800000;
	mov.f32 	%f2, 0f3F800000;
	selp.f32 	%f3, 0f3F800000, %f1, %p5;
	selp.f32 	%f4, 0f00000000, %f3, %p4;
	sub.ftz.f32 	%f5, %f2, %f4;
	cvt.u64.u32 	%rd19, %r6;
	mul.lo.s64 	%rd20, %rd19, %rd10;
	mul.lo.s32 	%r15, %r1, 3;
	cvt.s64.s32 	%rd21, %r15;
	add.s64 	%rd22, %rd11, %rd21;
	add.s64 	%rd23, %rd7, %rd22;
	ld.global.u8 	%rs1, [%rd23];
	cvt.rn.f32.u16 	%f6, %rs1;
	add.s64 	%rd24, %rd13, %rd21;
	add.s64 	%rd25, %rd6, %rd24;
	ld.global.u8 	%rs2, [%rd25];
	cvt.rn.f32.u16 	%f7, %rs2;
	mul.ftz.f32 	%f8, %f5, %f7;
	fma.rn.ftz.f32 	%f9, %f4, %f6, %f8;
	setp.lt.ftz.f32 	%p6, %f9, 0f00000000;
	setp.gt.ftz.f32 	%p7, %f9, 0f437F0000;
	selp.f32 	%f10, 0f437F0000, %f9, %p7;
	add.ftz.f32 	%f11, %f10, 0f3F000000;
	selp.f32 	%f12, 0f3F000000, %f11, %p6;
	cvt.rzi.ftz.u32.f32 	%r16, %f12;
	add.s64 	%rd26, %rd20, %rd21;
	add.s64 	%rd27, %rd5, %rd26;
	st.global.u8 	[%rd27], %r16;
	ld.global.u8 	%rs3, [%rd23+1];
	cvt.rn.f32.u16 	%f13, %rs3;
	ld.global.u8 	%rs4, [%rd25+1];
	cvt.rn.f32.u16 	%f14, %rs4;
	mul.ftz.f32 	%f15, %f5, %f14;
	fma.rn.ftz.f32 	%f16, %f4, %f13, %f15;
	setp.lt.ftz.f32 	%p8, %f16, 0f00000000;
	setp.gt.ftz.f32 	%p9, %f16, 0f437F0000;
	selp.f32 	%f17, 0f437F0000, %f16, %p9;
	add.ftz.f32 	%f18, %f17, 0f3F000000;
	selp.f32 	%f19, 0f3F000000, %f18, %p8;
	cvt.rzi.ftz.u32.f32 	%r17, %f19;
	st.global.u8 	[%rd27+1], %r17;
	ld.global.u8 	%rs5, [%rd23+2];
	cvt.rn.f32.u16 	%f20, %rs5;
	ld.global.u8 	%rs6, [%rd25+2];
	cvt.rn.f32.u16 	%f21, %rs6;
	mul.ftz.f32 	%f22, %f5, %f21;
	fma.rn.ftz.f32 	%f23, %f4, %f20, %f22;
	setp.lt.ftz.f32 	%p10, %f23, 0f00000000;
	setp.gt.ftz.f32 	%p11, %f23, 0f437F0000;
	selp.f32 	%f24, 0f437F0000, %f23, %p11;
	add.ftz.f32 	%f25, %f24, 0f3F000000;
	selp.f32 	%f26, 0f3F000000, %f25, %p10;
	cvt.rzi.ftz.u32.f32 	%r18, %f26;
	st.global.u8 	[%rd27+2], %r18;

$L__BB5_2:
	ret;

}
	// .globl	composite_alpha_u8x3_solid
.visible .entry composite_alpha_u8x3_solid(
	.param .u64 composite_alpha_u8x3_solid_param_0,
	.param .u32 composite_alpha_u8x3_solid_param_1,
	.param .u64 composite_alpha_u8x3_solid_param_2,
	.param .u32 composite_alpha_u8x3_solid_param_3,
	.param .u32 composite_alpha_u8x3_solid_param_4,
	.param .u32 composite_alpha_u8x3_solid_param_5,
	.param .u8 composite_alpha_u8x3_solid_param_6,
	.param .u8 composite_alpha_u8x3_solid_param_7,
	.param .u8 composite_alpha_u8x3_solid_param_8,
	.param .u64 composite_alpha_u8x3_solid_param_9,
	.param .u32 composite_alpha_u8x3_solid_param_10
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<7>;
	.reg .f32 	%f<27>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<22>;


	ld.param.u8 	%rs3, [composite_alpha_u8x3_solid_param_8];
	ld.param.u8 	%rs2, [composite_alpha_u8x3_solid_param_7];
	ld.param.u8 	%rs1, [composite_alpha_u8x3_solid_param_6];
	ld.param.u64 	%rd1, [composite_alpha_u8x3_solid_param_0];
	ld.param.u32 	%r3, [composite_alpha_u8x3_solid_param_1];
	ld.param.u64 	%rd2, [composite_alpha_u8x3_solid_param_2];
	ld.param.u32 	%r4, [composite_alpha_u8x3_solid_param_3];
	ld.param.u32 	%r6, [composite_alpha_u8x3_solid_param_4];
	ld.param.u32 	%r7, [composite_alpha_u8x3_solid_param_5];
	ld.param.u64 	%rd3, [composite_alpha_u8x3_solid_param_9];
	ld.param.u32 	%r5, [composite_alpha_u8x3_solid_param_10];
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %ctaid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r1, %r9, %r8, %r10;
	mov.u32 	%r11, %ntid.y;
	mov.u32 	%r12, %ctaid.y;
	mov.u32 	%r13, %tid.y;
	mad.lo.s32 	%r2, %r12, %r11, %r13;
	setp.ge.s32 	%p1, %r1, %r6;
	setp.ge.s32 	%p2, %r2, %r7;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB6_2;

	cvta.to.global.u64 	%rd4, %rd3;
	cvta.to.global.u64 	%rd5, %rd1;
	cvta.to.global.u64 	%rd6, %rd2;
	cvt.u64.u32 	%rd7, %r3;
	cvt.s64.s32 	%rd8, %r2;
	mul.lo.s64 	%rd9, %rd7, %rd8;
	cvt.u64.u32 	%rd10, %r4;
	mul.lo.s64 	%rd11, %rd10, %rd8;
	add.s64 	%rd12, %rd6, %rd11;
	mul.wide.s32 	%rd13, %r1, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.f32 	%f1, [%rd14];
	setp.lt.ftz.f32 	%p4, %f1, 0f00000000;
	setp.gt.ftz.f32 	%p5, %f1, 0f3F800000;
	mov.f32 	%f2, 0f3F800000;
	selp.f32 	%f3, 0f3F800000, %f1, %p5;
	selp.f32 	%f4, 0f00000000, %f3, %p4;
	sub.ftz.f32 	%f5, %f2, %f4;
	cvt.u64.u32 	%rd15, %r5;
	mul.lo.s64 	%rd16, %rd15, %rd8;
	mul.lo.s32 	%r14, %r1, 3;
	cvt.s64.s32 	%rd17, %r14;
	add.s64 	%rd18, %rd9, %rd17;
	add.s64 	%rd19, %rd5, %rd18;
	ld.global.u8 	%rs4, [%rd19];
	cvt.rn.f32.u16 	%f6, %rs4;
	cvt.rn.f32.u16 	%f7, %rs1;
	mul.ftz.f32 	%f8, %f5, %f7;
	fma.rn.ftz.f32 	%f9, %f4, %f6, %f8;
	setp.lt.ftz.f32 	%p6, %f9, 0f00000000;
	setp.gt.ftz.f32 	%p7, %f9, 0f437F0000;
	selp.f32 	%f10, 0f437F0000, %f9, %p7;
	add.ftz.f32 	%f11, %f10, 0f3F000000;
	selp.f32 	%f12, 0f3F000000, %f11, %p6;
	cvt.rzi.ftz.u32.f32 	%r15, %f12;
	add.s64 	%rd20, %rd16, %rd17;
	add.s64 	%rd21, %rd4, %rd20;
	st.global.u8 	[%rd21], %r15;
	ld.global.u8 	%rs5, [%rd19+1];
	cvt.rn.f32.u16 	%f13, %rs5;
	cvt.rn.f32.u16 	%f14, %rs2;
	mul.ftz.f32 	%f15, %f5, %f14;
	fma.rn.ftz.f32 	%f16, %f4, %f13, %f15;
	setp.lt.ftz.f32 	%p8, %f16, 0f00000000;
	setp.gt.ftz.f32 	%p9, %f16, 0f437F0000;
	selp.f32 	%f17, 0f437F0000, %f16, %p9;
	add.ftz.f32 	%f18, %f17, 0f3F000000;
	selp.f32 	%f19, 0f3F000000, %f18, %p8;
	cvt.rzi.ftz.u32.f32 	%r16, %f19;
	st.global.u8 	[%rd21+1], %r16;
	ld.global.u8 	%rs6, [%rd19+2];
	cvt.rn.f32.u16 	%f20, %rs6;
	cvt.rn.f32.u16 	%f21, %rs3;
	mul.ftz.f32 	%f22, %f5, %f21;
	fma.rn.ftz.f32 	%f23, %f4, %f20, %f22;
	setp.lt.ftz.f32 	%p10, %f23, 0f00000000;
	setp.gt.ftz.f32 	%p11, %f23, 0f437F0000;
	selp.f32 	%f24, 0f437F0000, %f23, %p11;
	add.ftz.f32 	%f25, %f24, 0f3F000000;
	selp.f32 	%f26, 0f3F000000, %f25, %p10;
	cvt.rzi.ftz.u32.f32 	%r17, %f26;
	st.global.u8 	[%rd21+2], %r17;

$L__BB6_2:
	ret;

}


)ptx";

struct GlobalCuda {
  std::once_flag once;
  studiocast::maxine::CudaDriverApi cuda;
  bool ok = false;
  std::string err;
};

GlobalCuda &g() {
  static GlobalCuda s;
  return s;
}

bool EnsureCudaReady(studiocast::maxine::CudaDriverApi **out_cuda,
                     std::string *error_out) {
  if (error_out)
    error_out->clear();
  GlobalCuda &st = g();
  std::call_once(st.once, [&]() {
    std::string e;
    if (!st.cuda.Initialize(&e)) {
      st.err = e;
      st.ok = false;
      return;
    }
    st.ok = true;
  });
  if (!st.ok) {
    if (error_out)
      *error_out = st.err.empty() ? "CUDA unavailable" : st.err;
    return false;
  }
  std::string e;
  if (!st.cuda.EnsureContext(&e)) {
    if (error_out)
      *error_out = e;
    return false;
  }
  *out_cuda = &st.cuda;
  return true;
}

struct KernelState {
  bool loaded = false;
  studiocast::maxine::CUmodule module = nullptr;
  studiocast::maxine::CUfunction resize_f32 = nullptr;
  studiocast::maxine::CUfunction blur_h_u8x3 = nullptr;
  studiocast::maxine::CUfunction blur_v_u8x3 = nullptr;
  studiocast::maxine::CUfunction blur_h_f32 = nullptr;
  studiocast::maxine::CUfunction blur_v_f32 = nullptr;
  studiocast::maxine::CUfunction comp_bg = nullptr;
  studiocast::maxine::CUfunction comp_solid = nullptr;
};

KernelState &k() {
  static KernelState s;
  return s;
}

bool EnsureKernelsLoaded(studiocast::maxine::CudaDriverApi *cuda,
                         std::string *error_out) {
  if (error_out)
    error_out->clear();
  KernelState &st = k();
  if (st.loaded)
    return true;

  const auto &f = cuda->f();
  studiocast::maxine::CUresult rc = studiocast::maxine::CUDA_SUCCESS;
  std::string jit_log;
  if (f.cuModuleLoadDataEx) {
    char info[8192] = {0};
    char err[8192] = {0};

    studiocast::maxine::CUjit_option opts[] = {
        studiocast::maxine::CU_JIT_INFO_LOG_BUFFER,
        studiocast::maxine::CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES,
        studiocast::maxine::CU_JIT_ERROR_LOG_BUFFER,
        studiocast::maxine::CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES,
        studiocast::maxine::CU_JIT_LOG_VERBOSE,
    };
    void *vals[] = {
        info,
        reinterpret_cast<void *>(static_cast<std::size_t>(sizeof(info))),
        err,
        reinterpret_cast<void *>(static_cast<std::size_t>(sizeof(err))),
        reinterpret_cast<void *>(static_cast<std::size_t>(1)),
    };

    rc = f.cuModuleLoadDataEx(
        &st.module, kOpenCudaVbPtx,
        static_cast<unsigned int>(sizeof(opts) / sizeof(opts[0])), opts, vals);
    jit_log = std::string("PTX JIT info log:\n") + info +
              "\nPTX JIT error log:\n" + err;
  } else {
    rc = f.cuModuleLoadData(&st.module, kOpenCudaVbPtx);
  }
  if (rc != studiocast::maxine::CUDA_SUCCESS) {
    if (error_out) {
      *error_out = "cuModuleLoadData(open_cuda_vb_kernels) failed: " +
                   cuda->StatusToString(rc);
      if (!jit_log.empty())
        *error_out += "\n" + jit_log;
    }
    return false;
  }

  auto get_fn = [&](studiocast::maxine::CUfunction *out, const char *name) {
    const studiocast::maxine::CUresult st_rc =
        f.cuModuleGetFunction(out, st.module, name);
    if (st_rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = std::string("cuModuleGetFunction(") + name +
                     ") failed: " + cuda->StatusToString(st_rc);
      return false;
    }
    return true;
  };

  if (!get_fn(&st.resize_f32, "resize_bilinear_f32_1"))
    return false;
  if (!get_fn(&st.blur_h_u8x3, "box_blur_h_u8x3"))
    return false;
  if (!get_fn(&st.blur_v_u8x3, "box_blur_v_u8x3"))
    return false;
  if (!get_fn(&st.blur_h_f32, "box_blur_h_f32_1"))
    return false;
  if (!get_fn(&st.blur_v_f32, "box_blur_v_f32_1"))
    return false;
  if (!get_fn(&st.comp_bg, "composite_alpha_u8x3_bg"))
    return false;
  if (!get_fn(&st.comp_solid, "composite_alpha_u8x3_solid"))
    return false;

  st.loaded = true;
  return true;
}

bool CheckPitchU32(std::size_t pitch, const char *what,
                   std::string *error_out) {
  if (pitch > std::numeric_limits<std::uint32_t>::max()) {
    if (error_out)
      *error_out = std::string(what) + ": pitch too large for kernel ABI.";
    return false;
  }
  return true;
}

constexpr unsigned int kBlockX = 16;
constexpr unsigned int kBlockY = 16;

} // namespace

bool ResizeBilinearF32_1(const CudaImage &src, const CudaImage &dst,
                         studiocast::maxine::CUstream stream,
                         std::string *error_out) {
  if (error_out)
    error_out->clear();
  if (!src.Valid() || !dst.Valid()) {
    if (error_out)
      *error_out = "ResizeBilinearF32_1: invalid src/dst image.";
    return false;
  }
  if (src.format != PixelFormatGpu::f32_1 ||
      dst.format != PixelFormatGpu::f32_1) {
    if (error_out)
      *error_out = "ResizeBilinearF32_1: src/dst must be f32_1.";
    return false;
  }
  if (!CheckPitchU32(src.pitch, "ResizeBilinearF32_1(src)", error_out))
    return false;
  if (!CheckPitchU32(dst.pitch, "ResizeBilinearF32_1(dst)", error_out))
    return false;

  studiocast::maxine::CudaDriverApi *cuda = nullptr;
  if (!EnsureCudaReady(&cuda, error_out))
    return false;
  if (!EnsureKernelsLoaded(cuda, error_out))
    return false;

  KernelState &st = k();
  const auto &f = cuda->f();

  const std::uint32_t src_pitch = static_cast<std::uint32_t>(src.pitch);
  const std::uint32_t src_w = static_cast<std::uint32_t>(src.w);
  const std::uint32_t src_h = static_cast<std::uint32_t>(src.h);
  const std::uint32_t dst_pitch = static_cast<std::uint32_t>(dst.pitch);
  const std::uint32_t dst_w = static_cast<std::uint32_t>(dst.w);
  const std::uint32_t dst_h = static_cast<std::uint32_t>(dst.h);
  const unsigned long long src_ptr = src.ptr;
  const unsigned long long dst_ptr = dst.ptr;

  void *args[] = {
      const_cast<unsigned long long *>(&src_ptr),
      const_cast<std::uint32_t *>(&src_pitch),
      const_cast<std::uint32_t *>(&src_w),
      const_cast<std::uint32_t *>(&src_h),
      const_cast<unsigned long long *>(&dst_ptr),
      const_cast<std::uint32_t *>(&dst_pitch),
      const_cast<std::uint32_t *>(&dst_w),
      const_cast<std::uint32_t *>(&dst_h),
  };

  const unsigned int grid_x =
      (static_cast<unsigned int>(dst.w) + kBlockX - 1u) / kBlockX;
  const unsigned int grid_y =
      (static_cast<unsigned int>(dst.h) + kBlockY - 1u) / kBlockY;

  const studiocast::maxine::CUresult rc =
      f.cuLaunchKernel(st.resize_f32, grid_x, grid_y, 1, kBlockX, kBlockY, 1, 0,
                       stream, args, nullptr);
  if (rc != studiocast::maxine::CUDA_SUCCESS) {
    if (error_out)
      *error_out = "cuLaunchKernel(resize_bilinear_f32_1) failed: " +
                   cuda->StatusToString(rc);
    return false;
  }
  return true;
}

bool BoxBlurSeparableU8x3(const CudaImage &src, const CudaImage &tmp,
                          const CudaImage &dst, int radius,
                          studiocast::maxine::CUstream stream,
                          std::string *error_out) {
  if (error_out)
    error_out->clear();
  if (!src.Valid() || !tmp.Valid() || !dst.Valid()) {
    if (error_out)
      *error_out = "BoxBlurSeparableU8x3: invalid src/tmp/dst.";
    return false;
  }
  if (src.w != tmp.w || src.h != tmp.h || src.w != dst.w || src.h != dst.h) {
    if (error_out)
      *error_out = "BoxBlurSeparableU8x3: dimension mismatch.";
    return false;
  }
  if (src.format != tmp.format || src.format != dst.format) {
    if (error_out)
      *error_out = "BoxBlurSeparableU8x3: src/tmp/dst formats must match.";
    return false;
  }
  if (src.format != PixelFormatGpu::rgb_u8 &&
      src.format != PixelFormatGpu::bgr_u8) {
    if (error_out)
      *error_out = "BoxBlurSeparableU8x3: unsupported format (expected rgb_u8 "
                   "or bgr_u8).";
    return false;
  }
  if (!CheckPitchU32(src.pitch, "BoxBlurSeparableU8x3(src)", error_out))
    return false;
  if (!CheckPitchU32(tmp.pitch, "BoxBlurSeparableU8x3(tmp)", error_out))
    return false;
  if (!CheckPitchU32(dst.pitch, "BoxBlurSeparableU8x3(dst)", error_out))
    return false;

  radius = radius < 0 ? 0 : radius;

  studiocast::maxine::CudaDriverApi *cuda = nullptr;
  if (!EnsureCudaReady(&cuda, error_out))
    return false;

  // radius==0 is an identity operation; use a device-to-device copy to avoid
  // kernel edge cases.
  if (radius == 0) {
    const auto &f = cuda->f();
    studiocast::maxine::CUDA_MEMCPY2D cp{};
    cp.srcMemoryType = studiocast::maxine::CU_MEMORYTYPE_DEVICE;
    cp.srcDevice = src.ptr;
    cp.srcPitch = src.pitch;
    cp.dstMemoryType = studiocast::maxine::CU_MEMORYTYPE_DEVICE;
    cp.dstDevice = dst.ptr;
    cp.dstPitch = dst.pitch;
    cp.WidthInBytes = src.RowBytes();
    cp.Height = static_cast<std::size_t>(src.h);
    const auto rc = f.cuMemcpy2DAsync(&cp, stream);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuMemcpy2DAsync(BoxBlurSeparableU8x3 copy) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
    return true;
  }

  if (!EnsureKernelsLoaded(cuda, error_out))
    return false;

  KernelState &st = k();
  const auto &f = cuda->f();

  const std::uint32_t w = static_cast<std::uint32_t>(src.w);
  const std::uint32_t h = static_cast<std::uint32_t>(src.h);
  const std::uint32_t src_pitch = static_cast<std::uint32_t>(src.pitch);
  const std::uint32_t tmp_pitch = static_cast<std::uint32_t>(tmp.pitch);
  const std::uint32_t dst_pitch = static_cast<std::uint32_t>(dst.pitch);
  const unsigned long long src_ptr = src.ptr;
  const unsigned long long tmp_ptr = tmp.ptr;
  const unsigned long long dst_ptr = dst.ptr;
  int rad = radius;

  const unsigned int grid_x =
      (static_cast<unsigned int>(src.w) + kBlockX - 1u) / kBlockX;
  const unsigned int grid_y =
      (static_cast<unsigned int>(src.h) + kBlockY - 1u) / kBlockY;

  {
    void *args[] = {
        const_cast<unsigned long long *>(&src_ptr),
        const_cast<std::uint32_t *>(&src_pitch),
        const_cast<std::uint32_t *>(&w),
        const_cast<std::uint32_t *>(&h),
        const_cast<unsigned long long *>(&tmp_ptr),
        const_cast<std::uint32_t *>(&tmp_pitch),
        &rad,
    };
    const auto rc = f.cuLaunchKernel(st.blur_h_u8x3, grid_x, grid_y, 1, kBlockX,
                                     kBlockY, 1, 0, stream, args, nullptr);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuLaunchKernel(box_blur_h_u8x3) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
  }
  {
    void *args[] = {
        const_cast<unsigned long long *>(&tmp_ptr),
        const_cast<std::uint32_t *>(&tmp_pitch),
        const_cast<std::uint32_t *>(&w),
        const_cast<std::uint32_t *>(&h),
        const_cast<unsigned long long *>(&dst_ptr),
        const_cast<std::uint32_t *>(&dst_pitch),
        &rad,
    };
    const auto rc = f.cuLaunchKernel(st.blur_v_u8x3, grid_x, grid_y, 1, kBlockX,
                                     kBlockY, 1, 0, stream, args, nullptr);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuLaunchKernel(box_blur_v_u8x3) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
  }
  return true;
}

bool BoxBlurSeparableF32_1(const CudaImage &src, const CudaImage &tmp,
                           const CudaImage &dst, int radius,
                           studiocast::maxine::CUstream stream,
                           std::string *error_out) {
  if (error_out)
    error_out->clear();
  if (!src.Valid() || !tmp.Valid() || !dst.Valid()) {
    if (error_out)
      *error_out = "BoxBlurSeparableF32_1: invalid src/tmp/dst.";
    return false;
  }
  if (src.w != tmp.w || src.h != tmp.h || src.w != dst.w || src.h != dst.h) {
    if (error_out)
      *error_out = "BoxBlurSeparableF32_1: dimension mismatch.";
    return false;
  }
  if (src.format != PixelFormatGpu::f32_1 ||
      tmp.format != PixelFormatGpu::f32_1 ||
      dst.format != PixelFormatGpu::f32_1) {
    if (error_out)
      *error_out = "BoxBlurSeparableF32_1: src/tmp/dst must be f32_1.";
    return false;
  }
  if (!CheckPitchU32(src.pitch, "BoxBlurSeparableF32_1(src)", error_out))
    return false;
  if (!CheckPitchU32(tmp.pitch, "BoxBlurSeparableF32_1(tmp)", error_out))
    return false;
  if (!CheckPitchU32(dst.pitch, "BoxBlurSeparableF32_1(dst)", error_out))
    return false;

  radius = radius < 0 ? 0 : radius;

  studiocast::maxine::CudaDriverApi *cuda = nullptr;
  if (!EnsureCudaReady(&cuda, error_out))
    return false;

  // radius==0 is an identity operation; use a device-to-device copy to avoid
  // kernel edge cases.
  if (radius == 0) {
    const auto &f = cuda->f();
    studiocast::maxine::CUDA_MEMCPY2D cp{};
    cp.srcMemoryType = studiocast::maxine::CU_MEMORYTYPE_DEVICE;
    cp.srcDevice = src.ptr;
    cp.srcPitch = src.pitch;
    cp.dstMemoryType = studiocast::maxine::CU_MEMORYTYPE_DEVICE;
    cp.dstDevice = dst.ptr;
    cp.dstPitch = dst.pitch;
    cp.WidthInBytes = src.RowBytes();
    cp.Height = static_cast<std::size_t>(src.h);
    const auto rc = f.cuMemcpy2DAsync(&cp, stream);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuMemcpy2DAsync(BoxBlurSeparableF32_1 copy) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
    return true;
  }

  if (!EnsureKernelsLoaded(cuda, error_out))
    return false;

  KernelState &st = k();
  const auto &f = cuda->f();

  const std::uint32_t w = static_cast<std::uint32_t>(src.w);
  const std::uint32_t h = static_cast<std::uint32_t>(src.h);
  const std::uint32_t src_pitch = static_cast<std::uint32_t>(src.pitch);
  const std::uint32_t tmp_pitch = static_cast<std::uint32_t>(tmp.pitch);
  const std::uint32_t dst_pitch = static_cast<std::uint32_t>(dst.pitch);
  const unsigned long long src_ptr = src.ptr;
  const unsigned long long tmp_ptr = tmp.ptr;
  const unsigned long long dst_ptr = dst.ptr;
  int rad = radius;

  const unsigned int grid_x =
      (static_cast<unsigned int>(src.w) + kBlockX - 1u) / kBlockX;
  const unsigned int grid_y =
      (static_cast<unsigned int>(src.h) + kBlockY - 1u) / kBlockY;

  {
    void *args[] = {
        const_cast<unsigned long long *>(&src_ptr),
        const_cast<std::uint32_t *>(&src_pitch),
        const_cast<std::uint32_t *>(&w),
        const_cast<std::uint32_t *>(&h),
        const_cast<unsigned long long *>(&tmp_ptr),
        const_cast<std::uint32_t *>(&tmp_pitch),
        &rad,
    };
    const auto rc = f.cuLaunchKernel(st.blur_h_f32, grid_x, grid_y, 1, kBlockX,
                                     kBlockY, 1, 0, stream, args, nullptr);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuLaunchKernel(box_blur_h_f32_1) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
  }
  {
    void *args[] = {
        const_cast<unsigned long long *>(&tmp_ptr),
        const_cast<std::uint32_t *>(&tmp_pitch),
        const_cast<std::uint32_t *>(&w),
        const_cast<std::uint32_t *>(&h),
        const_cast<unsigned long long *>(&dst_ptr),
        const_cast<std::uint32_t *>(&dst_pitch),
        &rad,
    };
    const auto rc = f.cuLaunchKernel(st.blur_v_f32, grid_x, grid_y, 1, kBlockX,
                                     kBlockY, 1, 0, stream, args, nullptr);
    if (rc != studiocast::maxine::CUDA_SUCCESS) {
      if (error_out)
        *error_out = "cuLaunchKernel(box_blur_v_f32_1) failed: " +
                     cuda->StatusToString(rc);
      return false;
    }
  }
  return true;
}

bool CompositeAlphaU8x3(const CudaImage &fg, const CudaImage &bg,
                        const CudaImage &alpha, const CudaImage &out,
                        studiocast::maxine::CUstream stream,
                        std::string *error_out) {
  if (error_out)
    error_out->clear();
  if (!fg.Valid() || !bg.Valid() || !alpha.Valid() || !out.Valid()) {
    if (error_out)
      *error_out = "CompositeAlphaU8x3: invalid fg/bg/alpha/out.";
    return false;
  }
  if (fg.w != bg.w || fg.h != bg.h || fg.w != out.w || fg.h != out.h ||
      fg.w != alpha.w || fg.h != alpha.h) {
    if (error_out)
      *error_out = "CompositeAlphaU8x3: dimension mismatch.";
    return false;
  }
  if (fg.format != bg.format || fg.format != out.format) {
    if (error_out)
      *error_out = "CompositeAlphaU8x3: fg/bg/out formats must match.";
    return false;
  }
  if (fg.format != PixelFormatGpu::rgb_u8 &&
      fg.format != PixelFormatGpu::bgr_u8) {
    if (error_out)
      *error_out = "CompositeAlphaU8x3: unsupported fg/bg/out format.";
    return false;
  }
  if (alpha.format != PixelFormatGpu::f32_1) {
    if (error_out)
      *error_out = "CompositeAlphaU8x3: alpha must be f32_1.";
    return false;
  }
  if (!CheckPitchU32(fg.pitch, "CompositeAlphaU8x3(fg)", error_out))
    return false;
  if (!CheckPitchU32(bg.pitch, "CompositeAlphaU8x3(bg)", error_out))
    return false;
  if (!CheckPitchU32(alpha.pitch, "CompositeAlphaU8x3(alpha)", error_out))
    return false;
  if (!CheckPitchU32(out.pitch, "CompositeAlphaU8x3(out)", error_out))
    return false;

  studiocast::maxine::CudaDriverApi *cuda = nullptr;
  if (!EnsureCudaReady(&cuda, error_out))
    return false;
  if (!EnsureKernelsLoaded(cuda, error_out))
    return false;

  KernelState &st = k();
  const auto &f = cuda->f();

  const std::uint32_t w = static_cast<std::uint32_t>(fg.w);
  const std::uint32_t h = static_cast<std::uint32_t>(fg.h);
  const std::uint32_t fg_pitch = static_cast<std::uint32_t>(fg.pitch);
  const std::uint32_t bg_pitch = static_cast<std::uint32_t>(bg.pitch);
  const std::uint32_t a_pitch = static_cast<std::uint32_t>(alpha.pitch);
  const std::uint32_t out_pitch = static_cast<std::uint32_t>(out.pitch);
  const unsigned long long fg_ptr = fg.ptr;
  const unsigned long long bg_ptr = bg.ptr;
  const unsigned long long a_ptr = alpha.ptr;
  const unsigned long long out_ptr = out.ptr;

  void *args[] = {
      const_cast<unsigned long long *>(&fg_ptr),
      const_cast<std::uint32_t *>(&fg_pitch),
      const_cast<unsigned long long *>(&bg_ptr),
      const_cast<std::uint32_t *>(&bg_pitch),
      const_cast<unsigned long long *>(&a_ptr),
      const_cast<std::uint32_t *>(&a_pitch),
      const_cast<std::uint32_t *>(&w),
      const_cast<std::uint32_t *>(&h),
      const_cast<unsigned long long *>(&out_ptr),
      const_cast<std::uint32_t *>(&out_pitch),
  };

  const unsigned int grid_x =
      (static_cast<unsigned int>(fg.w) + kBlockX - 1u) / kBlockX;
  const unsigned int grid_y =
      (static_cast<unsigned int>(fg.h) + kBlockY - 1u) / kBlockY;

  const auto rc = f.cuLaunchKernel(st.comp_bg, grid_x, grid_y, 1, kBlockX,
                                   kBlockY, 1, 0, stream, args, nullptr);
  if (rc != studiocast::maxine::CUDA_SUCCESS) {
    if (error_out)
      *error_out = "cuLaunchKernel(composite_alpha_u8x3_bg) failed: " +
                   cuda->StatusToString(rc);
    return false;
  }
  return true;
}

bool CompositeAlphaSolidU8x3(const CudaImage &fg, const CudaImage &alpha,
                             std::uint8_t bg_r, std::uint8_t bg_g,
                             std::uint8_t bg_b, const CudaImage &out,
                             studiocast::maxine::CUstream stream,
                             std::string *error_out) {
  if (error_out)
    error_out->clear();
  if (!fg.Valid() || !alpha.Valid() || !out.Valid()) {
    if (error_out)
      *error_out = "CompositeAlphaSolidU8x3: invalid fg/alpha/out.";
    return false;
  }
  if (fg.w != out.w || fg.h != out.h || fg.w != alpha.w || fg.h != alpha.h) {
    if (error_out)
      *error_out = "CompositeAlphaSolidU8x3: dimension mismatch.";
    return false;
  }
  if (fg.format != out.format) {
    if (error_out)
      *error_out = "CompositeAlphaSolidU8x3: fg/out formats must match.";
    return false;
  }
  if (fg.format != PixelFormatGpu::rgb_u8 &&
      fg.format != PixelFormatGpu::bgr_u8) {
    if (error_out)
      *error_out = "CompositeAlphaSolidU8x3: unsupported fg/out format.";
    return false;
  }
  if (alpha.format != PixelFormatGpu::f32_1) {
    if (error_out)
      *error_out = "CompositeAlphaSolidU8x3: alpha must be f32_1.";
    return false;
  }
  if (!CheckPitchU32(fg.pitch, "CompositeAlphaSolidU8x3(fg)", error_out))
    return false;
  if (!CheckPitchU32(alpha.pitch, "CompositeAlphaSolidU8x3(alpha)", error_out))
    return false;
  if (!CheckPitchU32(out.pitch, "CompositeAlphaSolidU8x3(out)", error_out))
    return false;

  studiocast::maxine::CudaDriverApi *cuda = nullptr;
  if (!EnsureCudaReady(&cuda, error_out))
    return false;
  if (!EnsureKernelsLoaded(cuda, error_out))
    return false;

  KernelState &st = k();
  const auto &f = cuda->f();

  const std::uint32_t w = static_cast<std::uint32_t>(fg.w);
  const std::uint32_t h = static_cast<std::uint32_t>(fg.h);
  const std::uint32_t fg_pitch = static_cast<std::uint32_t>(fg.pitch);
  const std::uint32_t a_pitch = static_cast<std::uint32_t>(alpha.pitch);
  const std::uint32_t out_pitch = static_cast<std::uint32_t>(out.pitch);
  const unsigned long long fg_ptr = fg.ptr;
  const unsigned long long a_ptr = alpha.ptr;
  const unsigned long long out_ptr = out.ptr;
  const std::uint8_t r = bg_r;
  const std::uint8_t g = bg_g;
  const std::uint8_t b = bg_b;

  void *args[] = {
      const_cast<unsigned long long *>(&fg_ptr),
      const_cast<std::uint32_t *>(&fg_pitch),
      const_cast<unsigned long long *>(&a_ptr),
      const_cast<std::uint32_t *>(&a_pitch),
      const_cast<std::uint32_t *>(&w),
      const_cast<std::uint32_t *>(&h),
      const_cast<std::uint8_t *>(&r),
      const_cast<std::uint8_t *>(&g),
      const_cast<std::uint8_t *>(&b),
      const_cast<unsigned long long *>(&out_ptr),
      const_cast<std::uint32_t *>(&out_pitch),
  };

  const unsigned int grid_x =
      (static_cast<unsigned int>(fg.w) + kBlockX - 1u) / kBlockX;
  const unsigned int grid_y =
      (static_cast<unsigned int>(fg.h) + kBlockY - 1u) / kBlockY;

  const auto rc = f.cuLaunchKernel(st.comp_solid, grid_x, grid_y, 1, kBlockX,
                                   kBlockY, 1, 0, stream, args, nullptr);
  if (rc != studiocast::maxine::CUDA_SUCCESS) {
    if (error_out)
      *error_out = "cuLaunchKernel(composite_alpha_u8x3_solid) failed: " +
                   cuda->StatusToString(rc);
    return false;
  }
  return true;
}

} // namespace studiocast::cuda::kernels
