#!/usr/bin/env bash
set -euo pipefail

# StudioCast v4l2loopback helper.
#
# Installs and configures a v4l2loopback virtual camera device for StudioCast.
# This is required so OBS/Zoom/etc can see the "StudioCast Camera" virtual webcam.
#
# Notes:
# - Requires sudo for package install and module configuration.
# - The daemon keeps the writer FD open and seeds frames; this script only ensures the kernel module/device exist.

usage() {
  cat <<'EOF'
Usage:
  scripts/setup_v4l2loopback.sh [options]

Options:
  --install             Install v4l2loopback DKMS + dependencies via apt.
  --load                Load the v4l2loopback module now (creates /dev/videoN).
  --persist             Persist the module load/options across reboot.
  --video-nr N          Video device number (default: 10).
  --devices N           Number of loopback devices (default: 1).
  --label TEXT          Device label (default: "StudioCast Camera").
  --exclusive-caps 0|1  exclusive_caps setting (default: 1).
  -y, --yes             Assume yes for apt installs.
  -h, --help            Show help.

Examples:
  # Install packages, load module now, and persist across reboot:
  ./scripts/setup_v4l2loopback.sh --install --load --persist

  # Just load a device at /dev/video20 (no persistence):
  ./scripts/setup_v4l2loopback.sh --load --video-nr 20
EOF
}

YES=0
DO_INSTALL=0
DO_LOAD=0
DO_PERSIST=0
VIDEO_NR=10
DEVICES=1
LABEL="StudioCast Camera"
EXCLUSIVE_CAPS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install) DO_INSTALL=1; shift ;;
    --load) DO_LOAD=1; shift ;;
    --persist) DO_PERSIST=1; shift ;;
    --video-nr) VIDEO_NR="${2:-}"; shift 2 ;;
    --devices) DEVICES="${2:-}"; shift 2 ;;
    --label) LABEL="${2:-}"; shift 2 ;;
    --exclusive-caps) EXCLUSIVE_CAPS="${2:-}"; shift 2 ;;
    -y|--yes) YES=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1"; usage; exit 2 ;;
  esac
done

if [[ "$DO_INSTALL" -eq 1 ]]; then
  echo "[v4l2loopback] Installing packages..."
  APT_ARGS=()
  if [[ "$YES" -eq 1 ]]; then APT_ARGS+=("-y"); fi

  sudo apt update
  sudo apt install "${APT_ARGS[@]}"     dkms     linux-headers-$(uname -r)     v4l2loopback-dkms     v4l2loopback-utils     v4l-utils
fi

if [[ "$DO_LOAD" -eq 1 ]]; then
  echo "[v4l2loopback] Loading module now..."
  # shellcheck disable=SC2086
  sudo modprobe v4l2loopback devices="$DEVICES" video_nr="$VIDEO_NR" card_label="$LABEL" exclusive_caps="$EXCLUSIVE_CAPS"
  echo "[v4l2loopback] Loaded. Device should be at /dev/video${VIDEO_NR}"
  echo "[v4l2loopback] Verify with:"
  echo "  v4l2-ctl --list-devices"
fi

if [[ "$DO_PERSIST" -eq 1 ]]; then
  echo "[v4l2loopback] Persisting module load across reboot..."
  CONF_MODPROBE="/etc/modprobe.d/studiocast-v4l2loopback.conf"
  CONF_MODULES="/etc/modules-load.d/studiocast-v4l2loopback.conf"

  # Escape spaces for modprobe.d (card_label supports spaces but needs escaping).
  LABEL_ESCAPED="${LABEL// /\\ }"

  # Note: card_label can contain spaces, but modprobe.d requires escaping spaces.
  sudo tee "$CONF_MODPROBE" >/dev/null <<EOF
# Auto-generated by StudioCast: v4l2loopback options
options v4l2loopback devices=${DEVICES} video_nr=${VIDEO_NR} card_label=${LABEL_ESCAPED} exclusive_caps=${EXCLUSIVE_CAPS}
EOF

  sudo tee "$CONF_MODULES" >/dev/null <<EOF
# Auto-generated by StudioCast: load v4l2loopback on boot
v4l2loopback
EOF

  echo "[v4l2loopback] Wrote:"
  echo "  $CONF_MODPROBE"
  echo "  $CONF_MODULES"
  echo "[v4l2loopback] Reboot or run: sudo modprobe -r v4l2loopback && sudo modprobe v4l2loopback"
fi

echo "[v4l2loopback] Done."